### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by 5HT2** [TheAlphaEpsilon/Templar-Cosmetics-Beta#2]
Hi, I noticed this project doesn't have a license, aside from the forge licenses (which are autogenerated and you can remove just fine!!)

I would recommend adding a license so people can properly reuse and credit your code in their projects. I personally like MIT, and that's what I would suggest you use if you're unfamiliar with licenses. 

Without a license, legally your code is All Rights Reserved so nobody can do much with it aside from looking at it.

**Comment by thaqalayn** [comment]
templar mod skid coming soon

**Comment by thaqalayn** [comment]
strong

**Comment by 5HT2** [comment]
# :muscle:

**Comment by TheAlphaEpsilon** [comment]
Yeah sure I'll add it soon
